### ISSUE TITLE
The wikidata dump

### ISSUE THREAD

**Issue by 2213500360** [magkai/CONQUER#1]
Hi, I want to down the wikidata dump but I don't know which dump I should download at https://dumps.wikimedia.org/wikidatawiki/entities/
I can find the most recent dump latest-all.json.bz2 is only around 63G but not 2TB

THx

**Comment by 2213500360** [comment]
And can you provide filtered wikidata dump? THx

**Comment by magkai** [comment]
Hi,
we used the wikidata n-triples dump: latest-all.nt.gz.
We have now included our filtered wikidata dump in the Wikidata Core github. You can download it from there: https://github.com/PhilippChr/wikidata-core-for-QA

**Comment by 2213500360** [comment]
Thank you for the dump, but I had a problem when I importing it into Neo4j, which prompted the following error (on Windows system)：


nodes_literals.csv @ position 78179 -  there's a field starting with a quote and whereas it ends that quote there seems to be characters in that field after that ending quote. That isn't supported. This is what I read: 'Douglas Adams"-'


The error seems to be caused by the string "-gb" outside double quotation marks. So what is the meaning of "-gb" and how to solve this problem? Can I traverse the rows in wikidata_clean and when "-gb" is appear delete them ? It seems to take a lot of time.

**Comment by 2213500360** [comment]
It took me 10 hours to delete "-gb" before I found out there was "- ca" . I seem to be spending another 10 hours deleting "- ca" as well.

**Comment by magkai** [comment]
I am a bit busy right now, but I will look into this. Can you give me a few more details:
 - Which version of neo4j are you using? Also note that this was only tested on Linux with neo4j-community-4.0.5 version. 
 - Have you used our loadKGIntoNeo4j.sh script? Make sure to use the respective parameters to skip "bad" entries.
 - Have you used the nodes_literals.csv provided in  https://conquer.mpi-inf.mpg.de/static/dumps.zip?

**Comment by 2213500360** [comment]
Because I use the windows system, I use the neo4j-community-4.3.2-windows version.
I used the neo4j-admin import  in the script you provided, and I didn't change it.
The nodes_literals.csv file I used is not obtained from this link, but it is obtained by running your program splitKGnodes.py.
Maybe the problem lies in the system or version. I will try to import it again after deleting "-ca". If not success, I will try to re install neo4j-community-4.0.5 .
THX

**Comment by 2213500360** [comment]
I download the nodes_literals.csv you provided in https://conquer.mpi-inf.mpg.de/static/dumps.zip, I found that it was different from the file I generated by running splitkgnodes. py, it has no "-gb" and "- ca" strings, So I wonder if there is something wrong with the wikidata_clean.csv file you provided in https://github.com/PhilippChr/wikidata-core-for-QA, because  the wikidata_clean.csv file you provided has "-gb" and "- ca" strings， so that I used the program in kg_processing to generate the wrong nodes_ literals.csv

**Comment by magkai** [comment]
Ok, thanks. I will look into this and then come back to you.

**Comment by magkai** [comment]
I have updated the dump at  https://github.com/PhilippChr/wikidata-core-for-QA and added a further script for cleaning literals, so that loading into neo4j should also work now with starting from the provided dump.
