### ISSUE TITLE
no cleaned_nodes_literals.csv in dump.zip

### ISSUE THREAD

**Issue by lihuiliullh** [magkai/CONQUER#10]
Can you check whether cleaned_nodes_literals.csv in dumps.zip?
I meet a problem when running bash loadKGIntoNeo4j.sh

Invalid value for option '--nodes' at index 0 ([<label>[:<label>]...=]<files>): Invalid nodes file: node_headers.csv/data/dumps/cleaned_nodes_literals.csv (java.lang.IllegalArgumentException:

**Comment by magkai** [comment]
Hi,

you can create the `cleaned_nodes_literals.csv` by executing` cleanLiterals.py `

Best Regards,
Magdalena
