### ISSUE TITLE
Candidate Answer Selection

### ISSUE THREAD

**Issue by SRL94** [magkai/CONQUER#4]
Could you please tell me how you select candidate answers? Which function of the codes refers to this part? Thank you.

**Comment by magkai** [comment]
Hi, 
thank you for your interest in our work.
The top predicted actions from our RL agents lead to the candidate answers. These are ranked according to the prediction scores coming from our policy network and if several agents predict the same answer entity the respective scores are added.
The candidate answers are returned from the `findAnswer()` method in the `rlEval.py` script in the `main` folder. In `findAnswer()`, the `call_rl()` method is called which returns the top k predictions from our network. 
I hope this helps.

Best Regards,
Magdalena

**Comment by SRL94** [comment]
Hi Magdalena,

Thanks for the detailed explanation! One more question about extracting paths that contain context entities. What is the length of the paths? One-hop?

Best regards
Sirui

**Comment by magkai** [comment]
Hi Sirui,

yes,  the paths are one-hop. However, please note that in our KG representation we can reach information connected via qualifier statements also in one-hop, while this would usually be two-hop connections in other representations. You can also have a look at our [paper](https://dl.acm.org/doi/10.1145/3404835.3462859) for further details about our KG representation.

Best Regards,
Magdalena
