### ISSUE TITLE
Question Types

### ISSUE THREAD

**Issue by SRL94** [magkai/CONQUER#5]
Hi,

Does this model only work for questions whose answers are entities? That is, it cannot handle count, comparison and "Yes or No" questions. Looking forward to your reply.

Best regards
Sirui

**Comment by magkai** [comment]
Hi Sirui,

CONQUER can deal with entities and literals (like names, numbers, dates, etc.) as answers. We do not provide explicit mechanisms for handling more complex types, like comparison questions.

Best Regards,
Magdalena

**Comment by SRL94** [comment]
Hi Magdalena,

Does CONQUER only work for one-hop questions?

Best regards
Sirui

**Comment by magkai** [comment]
Hi Sirui,

we currently walk one-hop in CONQUER. However, in the CONQUER KG representation we can reach information connected via qualifier statements also in one-hop, while this would usually be two-hop connections in other representations. Therefore, apart from simple questions, like: "Who is the author of Harry Potter?", we can also answer more complex questions like "Who played Batman in the Dark Knight movie?" or "Who did he marry in 2017?", "When was the movie released in Germany?" which require qualifier information.

Best Regards,
Magdalena
