### ISSUE TITLE
id2wikidata file

### ISSUE THREAD

**Issue by peyote-e** [magkai/CONQUER#7]
Hi there,

where can I find the id2wikidata.json file which is needed in the context_entity_detection/contextEntityRetrieval.py  (line 69)?

`d2wikidata = json.load(open("models/id2wikidata.json"))`  

Thank you in advance,

Ellis

**Comment by peyote-e** [comment]
Ah ok it is a file that is loaded from Blink...

**Comment by magkai** [comment]
Hi Ellis,

yes exactly, the id2wikidata.json file is created automatically by the ELQ dependency we use: https://github.com/facebookresearch/BLINK/blob/main/elq/main_dense.py (line 132). You just need to make sure that you created a directory named "models" inside context_entity_detection. 

Best Regards,
Magdalena
